supra_mileage:
    resource: "@SupraMileageBundle/Controller/"
    type:     annotation
    prefix:   /mileage/

tutorial_todo:
    resource: "@TutorialTodoBundle/Controller/"
    type:     annotation
    prefix:   /tut/
