Supra\Bundle\MileageBundle\Entity\Location:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        street:
            type: string
            length: 255
        city:
            type: string
            length: 64
        state:
            type: string
            length: 32
        zip:
            type: string
            length: 16
        suiteAptNo:
            type: string
            length: 32
            nullable: true
    lifecycleCallbacks: {  }
    manyToOne:
        client:
            targetEntity: Client
            inversedBy: locations
    manyToMany:
        trips:
            targetEntity: Trip
            mappedBy: locations
            
