Supra\Bundle\MileageBundle\Entity\Location:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        address:
            type: string
            length: 255
    lifecycleCallbacks: {  }
    manyToOne:
        client:
            targetEntity: Client
            inversedBy: locations
    manyToMany:
        trips:
            targetEntity: Trip
            mappedBy: locations
            
