Supra\Bundle\MileageBundle\Entity\Trip:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        travelTime:
            type: float
            nullable: true
        mileage:
            type: float
            nullable: true
        createdAt:
            type: datetime
            nullable: true
        tripDate:
            type: datetime
            nullable: true
        purpose: 
            type: text
            nullable: true
        unlisted_address:
            type: text
            nullable: true
    lifecycleCallbacks:
        prePersist: [ prePersist ]
    manyToMany:
        locations:
            targetEntity: Location
            inversedBy: trips
            joinTable:
                name: location_trips
                joinColumns: 
                    trip_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    location_id:
                        referencedColumnName: id
    manyToOne:
        client:
            targetEntity: Client
            inversedBy: trips
