supra_mileage_trip:
    resource: "@SupraMileageBundle/Resources/config/routing/trip.yml"
    prefix:   /trip

SupraMileageBundle_client:
    resource: "@SupraMileageBundle/Resources/config/routing/client.yml"
    prefix:   /client

SupraMileageBundle_location:
    resource: "@SupraMileageBundle/Resources/config/routing/location.yml"
    prefix:   /location
